### ISSUE TITLE
forgot password functionality

### ISSUE THREAD

**Issue by uptownhr** [uptownhr/hackathon-starter-lite#117]
- [ ] Create forgot password link on login page
- [ ] Create forgot password page with email form
- [ ] Send reset password email to email if email is found
  - Reset token should be generated and saved in User db
  - Reset token should be sent with the reset password link
- [ ] Create reset password url
  - Reads in reset token
  - if token matches email, redirect to new password page
- [ ] save new password
- [ ] implement nodemailer interface for sending emails
  - create smtp info area in config
  - update documentation mentioning the smtp config

**Comment by uptownhr** [comment]
deciding not to work on this feature

**Comment by niallobrien** [comment]
@uptownhr Is this something you don't want in the project, or simply something you'd rather not do yourself?

**Comment by uptownhr** [comment]
I'd love this in the project actually, but decided I will not be working on this feature
