### ISSUE TITLE
Update Instragram Application Setting

### ISSUE THREAD

**Issue by uptownhr** [uptownhr/hackathon-starter-lite#18]
Currently attempting to login with a user returns. 

```
{
"code": 403,
"error_type": "OAuthForbiddenException",
"error_message": "You are not a sandbox user of this client"
}
```

I believe this is due to the application being in the sandbox state and I am not an authorized user for the application. We need to allow any users login and I think we have two options.
1. Remove sandbox mode, and put in live state.
2. Check if we can allow all users under sandbox mode. 

So if option 2 is not possible, lets use option 1.

**Comment by mochacat** [comment]
Can't go live yet: https://www.instagram.com/developer/review/

> To go Live and fully access Instagram content, you will need to submit your application for review and approval.

**Comment by uptownhr** [comment]
Ok. We will just close this for now. Not much we can do about it.
